stop_charging:
  description: "Stop/pause charging"
  fields:
    charger_id:
      required: true
      description: "The charger id"
      example: "yyyyyyyy-9999-99xx-xxxx-yyyyyyyyyyyy"

resume_charging:
  description: "Resume/start charging"
  fields:
    charger_id:
      required: true
      description: "The charger id"
      example: "yyyyyyyy-9999-99xx-xxxx-yyyyyyyyyyyy"

authorize_charging:
  description: "Authorize charging"
  fields:
    charger_id:
      required: true
      description: "The charger id"
      example: "yyyyyyyy-9999-99xx-xxxx-yyyyyyyyyyyy"

deauthorize_charging:
  description: "Deauthorize charging and stop"
  fields:
    charger_id:
      required: true
      description: "The charger id"
      example: "yyyyyyyy-9999-99xx-xxxx-yyyyyyyyyyyy"

restart_charger:
  description: "Restart charger."
  fields:
    charger_id:
      required: true
      description: "The charger id"
      example: "yyyyyyyy-9999-99xx-xxxx-yyyyyyyyyyyy"

update_firmware:
  description: "New resume command."
  fields:
    charger_id:
      required: true
      description: "Update the firmware."
      example: "yyyyyyyy-9999-99xx-xxxx-yyyyyyyyyyyy"

limit_current:
  description: "Update available current for the installation."
  fields:
    installation_id:
      required: true
      description: "The installation id"
      example: "yyyyyyyy-9999-99xx-xxxx-yyyyyyyyyyyy"
    available_current:
      description: "The available current for all phases. Cannot be used together with any available_current_phase* fields"
      example: "16"
    available_current_phase1:
      description: "The available current for phase 1"
      example: "16"
    available_current_phase2:
      description: "The available current for phase 2"
      example: "16"
    available_current_phase3:
      description: "The available current for phase 3"
      example: "16"
